<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Subak;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create superadmin user
        User::firstOrCreate(
            ['email' => 'admin@subakbali.com'],
            [
                'name' => 'I Gusti Ketut Ngurah Adi Putra',
                'password' => Hash::make('subakbali2025'),
                'role' => 'superadmin',
            ]
        );

        // Create 8 subak dummy data
        $subaks = [
            [
                'nama' => 'Subak Gemuh',
                'kabupaten' => 'Tabanan',
                'kecamatan' => 'Pupuan',
                'desa' => 'Belimbing',
                'luas_subak' => '50 Hektar',
                'jumlah_anggota' => '70 KK Orang',
                'nama_pekaseh' => 'I Nengah Sunarta',
                'no_telp' => '081339018457',
                'sumber_air' => 'Sungai',
                'kecukupan_kemarau' => 'Cukup',
                'kecukupan_hujan' => 'Cukup',
                'sistem_pembagian_air' => 'Kombinasi (Tektekan)',
                'panjang_saluran_primer' => '2 Km',
                'panjang_saluran_sekunder' => '0.1 Km',
                'panjang_saluran_tersier' => '0.1 Km',
                'kondisi_permanen' => '1.2 Km',
                'kondisi_tidak_permanen' => '0.8 Km',
                'kondisi_tembuku_arya' => 'Rusak',
                'kondisi_tembuku_gede' => 'Rusak',
                'kondisi_tembuku_pemaron' => 'Rusak',
                'keberadaan_sampah' => 'Bersih (tidak ada sampah)',
                'pencemaran_ternak' => 'Bersih (tidak ada limbah)',
                'pencemaran_industri' => 'Bersih (tidak ada limbah)',
                'pola_tanam' => 'Padi-Padi',
                'intensitas_tanam' => '2 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '5.8 Ton/Hektar',
                'varietas' => 'Ciherang',
            ],
            [
                'nama' => 'Subak Patebuan',
                'kabupaten' => 'Tabanan',
                'kecamatan' => 'Selemadeg',
                'desa' => 'Wanagiri',
                'luas_subak' => '69 Hektar',
                'jumlah_anggota' => '120 Orang',
                'nama_pekaseh' => 'Ketut Artha Giri',
                'no_telp' => '085237845640',
                'sumber_air' => 'Mata Air',
                'kecukupan_kemarau' => 'Cukup',
                'kecukupan_hujan' => 'Berlebih',
                'sistem_pembagian_air' => 'Tektekan dan Berdasar Luas Lahan',
                'panjang_saluran_primer' => '2 Km',
                'panjang_saluran_sekunder' => '1.8 Km',
                'panjang_saluran_tersier' => '1.5 Km',
                'kondisi_permanen' => '1 Km',
                'kondisi_tidak_permanen' => '5.3 Km',
                'kondisi_tembuku_arya' => 'Cukup Baik',
                'kondisi_tembuku_gede' => 'Cukup Baik',
                'kondisi_tembuku_pemaron' => 'Cukup Baik',
                'keberadaan_sampah' => 'Ada sampah tapi tidak mengganggu',
                'pencemaran_ternak' => 'Bersih',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Padi',
                'intensitas_tanam' => '2 kali tanam dalam 1 tahun',
                'alih_fungsi_1_tahun' => '60 Hektar',
                'peruntukan_1_tahun' => 'Villa dan Perumahan',
                'alih_fungsi_5_tahun' => '60 Hektar',
                'peruntukan_5_tahun' => 'Villa dan Perumahan',
                'produktivitas_padi' => '4 Ton/Hektar',
                'varietas' => 'Impari',
            ],
            [
                'nama' => 'Subak Anggabaya',
                'kabupaten' => 'Denpasar',
                'kecamatan' => 'Denpasar Timur',
                'desa' => 'Penatih',
                'luas_subak' => '35 Hektar',
                'jumlah_anggota' => '61 Orang',
                'nama_pekaseh' => 'I Made Wija',
                'no_telp' => '087862138075',
                'sumber_air' => 'DAS Kedewatan',
                'kecukupan_kemarau' => 'Cukup',
                'kecukupan_hujan' => 'Cukup',
                'solusi_kekurangan_air' => 'Nyilih Yeh',
                'sistem_pembagian_air' => 'Tradisional dan Proporsional Luas Lahan',
                'panjang_saluran_primer' => '1 Km',
                'panjang_saluran_sekunder' => '0.7 Km',
                'panjang_saluran_tersier' => '2 Km',
                'kondisi_permanen' => '0.7 Km',
                'kondisi_tidak_permanen' => '2.3 Km',
                'kondisi_tembuku_arya' => 'Cukup Baik',
                'kondisi_tembuku_gede' => 'Cukup Baik',
                'kondisi_tembuku_pemaron' => 'Baik',
                'keberadaan_sampah' => 'Bersih',
                'pencemaran_ternak' => 'Bersih',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Padi',
                'intensitas_tanam' => '2 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '5 Ton/Hektar',
                'varietas' => 'Ciherang',
            ],
            [
                'nama' => 'Subak Padanggalak',
                'kabupaten' => 'Denpasar',
                'kecamatan' => 'Denpasar Timur',
                'desa' => 'Kesiman',
                'luas_subak' => '42 Hektar',
                'jumlah_anggota' => '182 Orang',
                'nama_pekaseh' => 'I Ketut Losen',
                'no_telp' => '08164709407',
                'sumber_air' => 'Tukad Ayung',
                'kecukupan_kemarau' => 'Cukup',
                'kecukupan_hujan' => 'Kelebihan',
                'solusi_kekurangan_air' => 'Magilihan',
                'sistem_pembagian_air' => 'Berdasarkan Ayahan dan Proporsional Luas Lahan',
                'panjang_saluran_primer' => '5 Km',
                'panjang_saluran_sekunder' => '4.5 Km',
                'panjang_saluran_tersier' => '6 Km',
                'kondisi_permanen' => '10.85 Km',
                'kondisi_tidak_permanen' => '4.65 Km',
                'kondisi_tembuku_arya' => 'Baik',
                'kondisi_tembuku_gede' => 'Baik',
                'kondisi_tembuku_pemaron' => 'Baik',
                'keberadaan_sampah' => 'Banyak sampah dan mengganggu',
                'pencemaran_ternak' => 'Ada pencemaran',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Padi-Palawija',
                'intensitas_tanam' => '3 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '6 Ton/Hektar',
                'varietas' => 'IR64',
            ],
            [
                'nama' => 'Subak Kedua',
                'kabupaten' => 'Gianyar',
                'kecamatan' => 'Ubud',
                'desa' => 'Kedewatan',
                'luas_subak' => '78 Hektar',
                'jumlah_anggota' => '181 Orang',
                'nama_pekaseh' => 'I Wayan Sija',
                'no_telp' => '082236820977',
                'sumber_air' => 'DI Kedewatan, Natak Tiis',
                'kecukupan_kemarau' => 'Kekurangan',
                'kecukupan_hujan' => 'Kelebihan',
                'solusi_kekurangan_air' => 'Megilihan',
                'sistem_pembagian_air' => 'Berdasarkan Ayahan dan Ayahan Tenaga',
                'panjang_saluran_primer' => '2.5 Km',
                'panjang_saluran_sekunder' => '18 Km',
                'panjang_saluran_tersier' => '0 Km',
                'kondisi_permanen' => '10.5 Km',
                'kondisi_tidak_permanen' => '10 Km',
                'kondisi_tembuku_arya' => 'Cukup Baik',
                'kondisi_tembuku_gede' => 'Rusak',
                'kondisi_tembuku_pemaron' => 'Cukup Baik',
                'keberadaan_sampah' => 'Ada sampah tapi tidak mengganggu',
                'pencemaran_ternak' => 'Bersih',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Padi',
                'intensitas_tanam' => '2 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '5.5 Ton/Hektar',
                'varietas' => 'Ciherang',
            ],
            [
                'nama' => 'Subak Umalayu',
                'kabupaten' => 'Gianyar',
                'kecamatan' => 'Sukawati',
                'desa' => 'Batuan',
                'luas_subak' => '55 Hektar',
                'jumlah_anggota' => '69 Orang',
                'nama_pekaseh' => 'I Made Suarta',
                'no_telp' => '085238269596',
                'sumber_air' => 'DAS Kedewatan',
                'kecukupan_kemarau' => 'Kurang',
                'kecukupan_hujan' => 'Melebihi',
                'solusi_kekurangan_air' => 'Nyilih Yeh di Pesedahan Yeh Lau',
                'sistem_pembagian_air' => 'Tradisional dan Proporsional Luas Lahan',
                'panjang_saluran_primer' => '0 Km',
                'panjang_saluran_sekunder' => '1.5 Km',
                'panjang_saluran_tersier' => '2 Km',
                'kondisi_permanen' => '0.7 Km',
                'kondisi_tidak_permanen' => '2.8 Km',
                'kondisi_tembuku_arya' => 'Cukup Baik',
                'kondisi_tembuku_gede' => 'Baik',
                'kondisi_tembuku_pemaron' => 'Baik',
                'keberadaan_sampah' => 'Bersih',
                'pencemaran_ternak' => 'Bersih',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Palawija',
                'intensitas_tanam' => '2 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '4.5 Ton/Hektar',
                'varietas' => 'Impari',
            ],
            [
                'nama' => 'Subak Pakel II',
                'kabupaten' => 'Badung',
                'kecamatan' => 'Mengwi',
                'desa' => 'Sading',
                'luas_subak' => '125 Hektar',
                'jumlah_anggota' => '125 Orang',
                'nama_pekaseh' => 'I Nyoman Narta',
                'no_telp' => '081999371608',
                'sumber_air' => 'DI Mambal, DAM Tanah Putih',
                'kecukupan_kemarau' => 'Kekurangan',
                'kecukupan_hujan' => 'Kelebihan',
                'solusi_kekurangan_air' => 'Natak Tiyis di Subak Uma Sangiyang, Badung',
                'sistem_pembagian_air' => 'Berdasarkan Ayahan dan Proporsional Luas Lahan',
                'panjang_saluran_primer' => '0 Km',
                'panjang_saluran_sekunder' => '0.5 Km',
                'panjang_saluran_tersier' => '7.5 Km',
                'kondisi_permanen' => '3 Km',
                'kondisi_tidak_permanen' => '5 Km',
                'kondisi_tembuku_arya' => 'Cukup Baik',
                'kondisi_tembuku_gede' => 'Baik',
                'kondisi_tembuku_pemaron' => 'Baik',
                'keberadaan_sampah' => 'Ada sampah tapi tidak mengganggu',
                'pencemaran_ternak' => 'Bersih',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Padi-Palawija',
                'intensitas_tanam' => '3 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '5 Ton/Hektar',
                'varietas' => 'Ciherang',
            ],
            [
                'nama' => 'Subak Demung',
                'kabupaten' => 'Tabanan',
                'kecamatan' => 'Tabanan',
                'desa' => 'Pejanten',
                'luas_subak' => '235 Hektar',
                'jumlah_anggota' => '235 Orang',
                'nama_pekaseh' => 'I Ketut Sunada',
                'no_telp' => '081999540950',
                'sumber_air' => 'Bendungan Yeh Panahan',
                'kecukupan_kemarau' => 'Baik tercukupi',
                'kecukupan_hujan' => 'Baik tercukupi',
                'solusi_kekurangan_air' => '-',
                'sistem_pembagian_air' => 'Tektek (1 tektek untuk 10 are)',
                'panjang_saluran_primer' => '5 Km',
                'panjang_saluran_sekunder' => '0.5 Km',
                'panjang_saluran_tersier' => '2.8 Km',
                'kondisi_permanen' => '3.3 Km',
                'kondisi_tidak_permanen' => '5 Km',
                'kondisi_tembuku_arya' => 'Baik',
                'kondisi_tembuku_gede' => 'Baik',
                'kondisi_tembuku_pemaron' => 'Baik',
                'keberadaan_sampah' => 'Bersih',
                'pencemaran_ternak' => 'Bersih',
                'pencemaran_industri' => 'Bersih',
                'pola_tanam' => 'Padi-Padi',
                'intensitas_tanam' => '2 kali tanam dalam 1 tahun',
                'produktivitas_padi' => '6.2 Ton/Hektar',
                'varietas' => 'Ciherang',
            ],
        ];

        foreach ($subaks as $subak) {
            Subak::firstOrCreate(['nama' => $subak['nama']], $subak);
        }
    }
}
